spring:
  profiles:
    active: local
---
server:
  port: 0

logging:
  level:
    yongs:
      temp: DEBUG
    com:
      netflix:
        eureka: OFF
        discovery: OFF
          
spring:
  config:
    activate:
      on-profile: local
  application:
    name: example-product
  data:
    mongodb:
      host: localhost
      port: 27017
      database: example
      authentication-database: admin
      username: scott
      password: tiger

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: true
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

minio:
  host: minio
  port: 9000
  
---
server:
  port: 8080

logging:
  level:
    yongs:
      temp: INFO
  
spring:
  config:
    activate:
      on-profile: container
  application:
    name: example-product
  data:
    mongodb:
      host: mongo
      port: 27017
      database: example
      authentication-database: admin
      username: scott
      password: tiger

eureka:
  instance:
    preferIpAddress: true
    hostname: example-eureka
    instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: true
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

minio:
  host: minio
  port: 9000