spring:
  profiles:
    active: window-dev
---
server:
  port: 8082
  
spring:
  profiles: window-dev
  application:
    name: example-product
  data:
    mongodb:
      username: scott
      password: tiger
      host: localhost
      port: 27017
      database: flex
          
logging:
  level:
    yongs:
      temp: DEBUG

minio:
  host: localhost
  port: 9000
  
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: true
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
---
server:
  port: 8080

spring:
  profiles: container
  application:
    name: example-product
  data:
    mongodb:
      username: scott
      password: tiger
      host: mongo-db
      port: 27017
      database: flex
      
logging:
  level:
    yongs:
      temp: INFO

minio:
  host: minio
  port: 9000
                           
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka
  client:
    registerWithEureka: true 
    fetchRegistry: true
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
            
