spring:
  profiles:
    active: local
---
server:
  port: 8082

logging:
  level:
    yongs:
      temp: DEBUG
  
spring:
  config:
    activate:
      on-profile: local
  application:
    name: example-product
  data:
    mongodb:
      host: localhost
      port: 27017
      database: example
      authentication-database: admin
      username: scott
      password: tiger

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: false
    fetchRegistry: false
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

minio:
  host: minio
  port: 9000